[build]
  # Nessun processo di build necessario - sito statico HTML/CSS/JS
  publish = "."
  
[build.environment]
  # Nessuna variabile d'ambiente richiesta

[[redirects]]
  # Redirect per SPA (se necessario)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["*"]}
  force = false

# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers specifici per i file JS/CSS
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"
